# Generated by Django 5.0.7 on 2024-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=127, verbose_name='Марка')),
                ('model', models.CharField(max_length=127, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('BE', 'Бензин'), ('DI', 'Дизель'), ('EL', 'Электричество'), ('GI', 'Гибрид')], max_length=15, verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('ME', 'Механическая'), ('AU', 'Автоматическая'), ('VA', 'Вариатор'), ('RO', 'Робот')], max_length=15, verbose_name='Тип КПП')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
