# Generated by Django 5.0.7 on 2024-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_alter_car_fuel_type_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электричество', 'Электричество'), ('Гибрид', 'Гибрид')], max_length=15, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Механическая', 'Механическая'), ('Автоматическая', 'Автоматическая'), ('Вариатор', 'Вариатор'), ('Робот', 'Робот')], max_length=15, verbose_name='Тип КПП'),
        ),
    ]
